##
# ArgoCD values
##

## Helm Repo GIT
helmRepoUrl: https://github.com/gitopsify/cp4i-gitops

# ArgoCD apps definition
apps:
  deploy-odf:
    branch: main
    enabled: true
    path: config/odf
    autosync: false
    namespace: openshift-storage
namespaces:
  - openshift-storage
  - openshift-machine-api
  - openshift-operators
  - openshift-gitops
