---
repoURL: https://github.com/gitopsify/cp4i-gitops
targetRevision: main
serviceaccount:
  ibm_cloudpaks_installer: ibm-cp4i-installer
  argocd_application_controller: openshift-gitops-argocd-application-controller
metadata:
  argocd_app_namespace: ibm-cloudpaks
  argocd_namespace: openshift-gitops
storageclass:
  rwo: ocs-storagecluster-ceph-rbd
  rwx: ocs-storagecluster-cephfs
modules:
  apic: true
  mq: true
  platform: true
  client: false
