---
repoURL: https://github.com/gitopsify/cp4i-gitops
targetRevision: main
serviceaccount:
  argocd_application_controller: openshift-gitops-argocd-application-controller
metadata:
  argocd_app_namespace: ibm-cloudpaks
  argocd_namespace: openshift-gitops
spec:
